kind: pipeline
name: default

steps:
  - name: Test Project
    image: maven:3.9.3-eclipse-temurin-20-alpine
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B 
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret:  discordID
      webhook_token: 
        from_secret:  discordToken
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
           build {{build.number}} failed. Fix me please. 
        {{/success}}
      tts: true
      username: appleboy
