kind: pipeline
name: default

steps:
  - name: Test Project
    image: maven:3.9.3-eclipse-temurin-20-alpine
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B 
