kind: pipeline
name: Test SchachProjekt

steps:
  - name: Test Project
    image: maven:3.9.3-eclipse-temurin-20-alpine
    commands:
      - apk add zip
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
      - mvn clean package
      - mkdir Schachprojekt
      - cp ./target/SchachPrjekt2-1.0-SNAPSHOT-jar-with-dependencies.jar ./Schachprojekt/SchachProjekt.jar
      - cp -r ./src/main/resources/.app ./Schachprojekt/.app
      - zip Schachprojekt Schachprojekt
      - tar -czvf Schachprojekt.tar.gz Schachprojekt
      - mkdir release
      - mv Schachprojekt.zip ./release/Schachprojekt.zip
      - mv Schachprojekt.tar.gz ./release/Schachprojekt.tar.gz
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret:  discordID
      webhook_token: 
        from_secret:  discordToken
      avatar_url: https://styles.redditmedia.com/t5_jt7nk/styles/communityIcon_62qfghr0oq931.png
      message: >
        {{#success build.status}}
          Build {{build.number}} succeeded. Good job {{build.author}}.
        {{else}}
           Build {{build.number}} failed. Fix me please. 
        {{/success}}
        Link: {{build.link}}
        
      username: Drone CI
  - name: publish
    image: plugins/github-release
#    commands:
#      - mkdir Schachprojekt
#      - cp ./target/SchachPrjekt2-1.0-SNAPSHOT-jar-with-dependencies.jar ./Schachprojekt/SchachPrjekt.jar
#      - cp ./src/main/resources/.app ./Schachprojekt/.app
    settings:
      title: Schachprojekt
      api_key:
        from_secret: githubApi
      files: release/*
    when:
      event: tag